# plugin prefix for messaging
prefix: "&7[O'DailyQuests&7]"

# storage mode for quests & progression
# AVAILABLE MODES: YAML, MySQL
storage_mode: "YAML"

# MySQL Database Connection
database:
  name: "MyDatabase"   # Database name
  host: "127.0.0.1"    # Database host
  user: "admin"        # Database user
  password: "1234"     # Database password
  port: "3306"         # Database port

# Select the mode of the quests.
# ==========================================================
# 1 : only the global quests will be loaded.
# The player's quests will only come from there.
# ==========================================================
# 2 : easy, medium and hard quests will be loaded.
# One quest per difficulty will be assigned to the players.
# ==========================================================
# You need to reset progressions if you change this mode.
quests_mode: 1

# Select the mode of timestamp.
# ============================================================================
# 1 : quests will be reloaded at midnight for all players.
# ============================================================================
# 2 : player quests will be reloaded if active quests are older
# than the duration selected temporality mode.
# This means that each player will have new quests at a different login time.
# ============================================================================
# The timestamp depends on the machine on which your server is installed.
# Set the right time zone!
# ============================================================================
# You need to reset progressions if you change this mode.
timestamp_mode: 1

# Select the mode of temporality.
# ===================================
# 1 : daily quests.
# ===================================
# 2 : weekly quests.
# ===================================
# 3 : monthly quests.
# ===================================
# You need to reset progressions
# if you change this mode.
temporality_mode: 1

# Initials that will be displayed
# between the values on the placeholders.
# ex: 6d9h24m
temporality_initials:
  days: "d"
  hours: "h"
  minutes: "m"

# Global Reward
# Will be given when the player has completed all their daily quests.
# The syntax is the same as for quest rewards.
global_reward:
  enabled: true
  reward_type: COMMAND
  commands:
    - "eco give %player% 5000"
    - "give %player% diamond_block 32"

# If a player has two quests of the same type and with the same item/entity,
# choose if they should progress simultaneously
# or if the first should be completed before the second progresses.
synchronised_progression: false

# interfaces settings
# NEVER DELETE A %variable%
# %progress% is replaced by the progression of the quest.
# %required% is replaced by the required amount to complete the quest.
# %achieved% is replaced by the number of completed quests.
# %drawIn% is replaced by the time remaining before the next quests draw.
interfaces:
  next_item_name: "&a&lNext Page"
  previous_item_name: "&e&lPrevious Page"
  player_quests:
    inventory_name: "&bMy quests"
    empty_item: GREEN_STAINED_GLASS_PANE
    progress: "&eIN PROGRESS (&a%progress%&e/&c%required%&e)"
    status: "&eStatus :"
    achieved: "&aACHIEVED"
    complete_get_type: "&eClick to complete this quest !"
    player_head:
      item_name: "&bYour quests"
      item_description:
        - "&eCompleted quests : &b%achieved%&e/&63"
        - "&eNext draw in : &c%drawIn%"
  global_quests:
    inventory_name: "Quests - Global"
    empty_item: BLACK_STAINED_GLASS_PANE
  easy_quests:
    inventory_name: "Quests - Easy"
    empty_item: GREEN_STAINED_GLASS_PANE
  medium_quests:
    inventory_name: "Quests - Medium"
    empty_item: YELLOW_STAINED_GLASS_PANE
  hard_quests:
    inventory_name: "Quests - Hard"
    empty_item: RED_STAINED_GLASS_PANE

# Citizens Implementation
# Here you can select NPCs names for each category.
# The player have to interact with the NPC to open an interface.
npcs:
  name_player: "&7Player Quests"
  name_global: "&4Global Quests"
  name_easy: "&a&lEasy &mQuests"
  name_medium: "&e&lMedium &rQuests"
  name_hard: "&cHard &b&lQuests"